
export enum AppStage {
  HOME = 'HOME',
  INPUT = 'INPUT',
  PACKAGING = 'PACKAGING',
  COMPLETED = 'COMPLETED',
  BROWSING = 'BROWSING',
  VIEWING = 'VIEWING',
  HISTORY = 'HISTORY'
}

export interface UserCanData {
  id: string;
  text: string;
  industry: string;
  adviceNeeded: string;
  mood: string;
  timestamp: string;
  ingredients?: string[]; // Generated by AI
}

export interface ReleasedSardine {
  id: string; // Unique ID for this interaction
  originalCanId: string;
  textLength: number;
  adviceGiven: string; // Includes stamps like [HUG]
  timestamp: string;
  industry: string;
}

export interface SardineState {
  isMouthOpen: boolean;
  isCrying: boolean;
  isTalking: boolean;
}
