export enum AppStage {
  INPUT = 'INPUT',
  PACKAGING = 'PACKAGING',
  COMPLETED = 'COMPLETED'
}

export interface UserCanData {
  text: string;
  industry: string;
  adviceNeeded: string;
  mood: string;
  timestamp: string;
  ingredients?: string[]; // Generated by AI
}

export interface SardineState {
  isMouthOpen: boolean;
  isCrying: boolean;
  isTalking: boolean;
}